#3202165 Organizer Page updates
MidCamp/midcamp pull request #399
Opened 2021-03-12 13:57 UTC by Brian-Clement

# Satisfies

[Rearrange Organizer Page #3202165](https://www.drupal.org/project/midcamp/issues/3202165)

# Description

- Exports production config
- Adds `field_leadership_year` to the `User` entity.  This is an entity reference field, targeting `event` terms consistent with how `field_organizer_year` is currently configured.
- Adds a Views attachment to the `organizers` View to show Leaders for a given year.
- Updates the `organizers` View to omit users who are both Organizers and Leaders to prevent them from displaying twice

# Test instructions

- Import configuration changes with `lando drush cim -y`
- Navigate to http://midcamp-org.lndo.site/admin/people and assign some users the `MidCamp 2021` value in `field_leadership_year`
- Navigate to http://midcamp-org.lndo.site/2021/organizers.  Observe these users appear in the upper "Leadership" portion of the page.  Observe they do not appear below with the rest of the Organizing team

# Screenshots

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/4048700/110949763-9b18c180-8308-11eb-958f-fad0fd962400.png">

2021-03-12 14:49 UTC, andrewolson commented on conf/drupal/config/views.view.organizers.yml
> +    display_title: '20201 Leadership Attachment'
Very minor change, but the year is wonky. Year currently is `20201`
Should be updated to `2021 Leadership Attachment`

2021-03-12 15:58 UTC, froboy commented on conf/drupal/config/core.menu.static_menu_link_overrides.yml
> +    enabled: true
I'd added a "get your ticket" link to the user menu a couple of days ago and it looks like it's not reflected here. Want to make sure that's not getting overridden.
![MidCamp_2021___March_24_-_27__2021](https://user-images.githubusercontent.com/238201/110965095-7f69e700-8319-11eb-9453-1e5b7c0161e7.png)

2021-03-12 16:01 UTC, froboy requested changes
From slack:

> I'd recommend killing MidCamp is organized by a group of volunteers from the Drupal community in Chicago, and beyond! from the view header and we can add it to the page instead

I also left one comment below about maybe missing config, otherwise this looks great.

2021-03-13 00:54 UTC, andrewolson commented
I have verified this in the test environment here: https://nginx.feature-3202165-organizer-page-updates.midcamp-org.us2.amazee.io/

If you can please fix the minor issues stated above, this is ready to merge. Thanks!

2021-03-13 20:29 UTC, merged